AhTask/AhTask.Web/Areas/Sitecore/Controllers/DeveloperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Areas.Sitecore.Controllers
{
    public class DeveloperController : Controller
    {
        // GET: Sitecore/Developer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SitecoreRocks()
        {
            return View();
        }

        public ActionResult Presentation()
        {
            return View();
        }

        public ActionResult Components()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Areas/Sitecore/Controllers/RealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Areas.Sitecore.Controllers
{
    public class RealController : Controller
    {
        // GET: Sitecore/Real
        public ActionResult Index()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Areas/Sitecore/Controllers/TrySitecoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Areas.Sitecore.Controllers
{
    public class TrySitecoreController : Controller
    {
        // GET: Sitecore/TrySitecore
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Installation()
        {
            return View();
        }

        public ActionResult Interface()
        {
            return View();
        }

        public ActionResult Templates()
        {
            return View();
        }

        public ActionResult Presentation ()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Controllers/GitHubController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Controllers
{
    public class GitHubController : Controller
    {
        // GET: GitHub
        public ActionResult Index()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Controllers/GlassMapperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Controllers
{
    public class GlassMapperController : Controller
    {
        // GET: GlassMapper
        public ActionResult Index()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Controllers/OctopusDeployController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Controllers
{
    public class OctopusDeployController : Controller
    {
        // GET: OctopusDeploy
        public ActionResult Index()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Controllers/SitecoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Controllers
{
    public class SitecoreController : Controller
    {
        // GET: Sitecore
        public ActionResult Index()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Controllers/TeamCityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Controllers
{
    public class TeamCityController : Controller
    {
        // GET: TeamCity
        public ActionResult Index()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Controllers/TeamDevelopmentSitecoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Controllers
{
    public class TeamDevelopmentSitecoreController : Controller
    {
        // GET: TeamDevelopmentSitecore
        public ActionResult Index()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Controllers/TeamFoundationServerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Controllers
{
    public class TeamFoundationServerController : Controller
    {
        // GET: TeamFoundationServer
        public ActionResult Index()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Controllers/TechController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AhTask.Web.Controllers
{
    public class TechController : Controller
    {
        // GET: Tech
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TeamFoundationServer()
        {
            return View();
        }

        public ActionResult TeamDevelopmentSitecore()
        {
            return View();
        }

        
        public ActionResult OctopusDeploy()
        {
            return View();
        }


        public ActionResult WindowsAzure()
        {
            return View();
        }

        public ActionResult Sitecore()
        {
            return View();
        }

        public ActionResult GlassMapper()
        {
            return View();
        }

        public ActionResult TeamCity()
        {
            return View();
        }

        public ActionResult GitHub()
        {
            return View();
        }
    }
}

AhTask/AhTask.Web/Areas/Sitecore/Views/Developer/Components.cshtml
@{
    ViewBag.Title = "Components";
    Layout = "~/Views/Shared/_LayoutSitecore.cshtml";
}

<h2>Components</h2>

AhTask/AhTask.Web/Areas/Sitecore/Views/Developer/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSitecore.cshtml";
}
<div class="jumbotron">
    <span class="well-sm label label-danger"><b>Sitecore</b></span><span class="well-sm label label-info"><b>Development</b></span>
    <h2 class="text-uppercase"><strong>Sitecore Developer</strong></h2>
    <p>Becomes a back-end Sitecore Developer.</p>
</div>

<blockquote>
    <h2>Course Description</h2>
    <p>
        Learn how to developer for  Sitecore by reviewing the basic concepts of Sitecore architecture. Try out this introductory course that was created with Sitecore Rocks.
    </p>
</blockquote>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Course Overview</h3>
    </div>
    <div class="panel-body">
        <div class="media">
            <div class="media-left">
                <a href="@Url.Action("SitecoreRocks", "Developer", new { Area="Sitecore"})">
                    <img class="media-object" src="~/App_Themes/Images/Icones/Sitecore/sitecoreInstallation.png" alt="...">
                </a>
            </div>
            <div class="media-body">
                <a href="@Url.Action("SitecoreRocks", "Developer", new { Area = "Sitecore" })">
                    <h4 class="media-heading"><b>Sitecore Rocks</b></h4>
                </a>
                <p>
                    Learn how to set up and connect the Sitecore Rocks with Sitecore Instance.
                </p>
                <p>
                    <a href="@Url.Action("SitecoreRocks", "Developer", new { Area = "Sitecore" })" class="btn btn-info">
                        <span class="glyphicon glyphicon-play-circle"></span> Watch Videos
                    </a>
                </p>
            </div>
        </div>       

        <div class="media">
            <div class="media-left">
                <a href="@Url.Action("Presentation", "Developer", new { Area = "Sitecore" })">
                    <img class="media-object" src="~/App_Themes/Images/Icones/Sitecore/SitecoreTemplate.png" alt="...">
                </a>
            </div>
            <div class="media-body">
                <a href="@Url.Action("Presentation", "Developer", new { Area = "Sitecore" })">
                    <h4 class="media-heading"><b>Presentation</b></h4>
                </a>
                <p>
                    Learn how to create layout and define the presentation details for it.
                </p>
                <p>
                    <a href="@Url.Action("Presentation", "Developer", new { Area = "Sitecore" })" class="btn btn-info">
                        <span class="glyphicon glyphicon-play-circle"></span> Watch Videos
                    </a>
                </p>
            </div>
        </div>
        <div class="media">
            <div class="media-left">
                <a href="@Url.Action("Components", "Developer", new { Area = "Sitecore" })">
                    <img class="media-object" src="~/App_Themes/Images/Icones/Sitecore/SitecoreTemplate.png" alt="...">
                </a>
            </div>
            <div class="media-body">
                <a href="@Url.Action("Components", "Developer", new { Area = "Sitecore" })">
                    <h4 class="media-heading"><b>Components</b></h4>
                </a>
                <p>
                    Learn how to create Sitecore componentes.
                </p>
                <p>
                    <a href="@Url.Action("Components", "Developer", new { Area = "Sitecore" })" class="btn btn-info">
                        <span class="glyphicon glyphicon-play-circle"></span> Watch Videos
                    </a>
                </p>
            </div>
        </div>

    </div>
</div>

AhTask/AhTask.Web/Areas/Sitecore/Views/Developer/Presentation.cshtml
@{
    ViewBag.Title = "Presentation";
    Layout = "~/Views/Shared/_LayoutSitecore.cshtml";
}

<h2>Presentation</h2>

AhTask/AhTask.Web/Areas/Sitecore/Views/Developer/SitecoreRocks.cshtml
@{
    ViewBag.Title = "SitecoreRocks";
    Layout = "~/Views/Shared/_LayoutSitecore.cshtml";
}

<h2>SitecoreRocks</h2>

AhTask/AhTask.Web/Areas/Sitecore/Views/Real/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSitecore.cshtml";
}

<h2>Index</h2>

AhTask/AhTask.Web/Views/GitHub/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

AhTask/AhTask.Web/Views/GlassMapper/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutTech.cshtml";
}

<h2>Index</h2>

AhTask/AhTask.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="jumbotron text-center">
    <h1>Welcome to AhTask <br /></h1>
    <p>
        The AhTask is a demo project that guide you through all different technologies involved in Athenahealth website project. Furthermore, it gives you a Sitecore’s fundamental base knowledge.
        The project by itself consist a small task manager.
        <br />
    </p>
    <p><a class="btn btn-primary" href="#" role="button">Learn more</a></p>
</div>
<div class="well">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/App_Themes/Images/Icones/github.png" alt="...">
                <div class="caption text-center">
                    <h3>GitHub</h3>
                    <p class="text-justify">
                        The source control used to keep track about all development process.
                        Also, it allows us to centralize and share the AhTask project with others Team development.
                        <br />
                    </p>
                    <p>
                        @Html.ActionLink("View Path", "GitHub", "Tech", null, new { @class = "btn btn-primary" })
                        <a href="https://github.com/Justimiano/AhTask" target="_blank" class="btn btn-warning" role="button">GitHub</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/App_Themes/Images/Icones/teamcity.png" alt="...">
                <div class="caption text-center">
                    <h3>Team City</h3>
                    <p class="text-justify">
                        We use the continuous integrations (CI) approach to building and testing our project automatically.
                        I found the TeamCity a great solution to implement the CI.
                    </p>
                    <p>
                        @Html.ActionLink("View Path", "TeamCity", "Tech", null, new { @class = "btn btn-primary" })
                        <a href="https://www.jetbrains.com/teamcity/" target="_blank" class="btn btn-warning" role="button">TeamCity</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/App_Themes/Images/Icones/octopus.jpg" alt="...">
                <div class="caption text-center">
                    <h3>Octopus Deploy</h3>
                    <p class="text-justify">
                        We use the continuous deploy (CD) to optimize the deployment process for each those environment we have been supporting the Athenahealth website project.
                    </p>
                    <p>
                        @Html.ActionLink("View Path", "OctopusDeploy", "Tech", null, new { @class = "btn btn-primary" })
                        <a href="http://octopusdeploy.com/" target="_blank" class="btn btn-warning" role="button">Octopus Deploy</a>
                    </p>
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/App_Themes/Images/Icones/GlassMapper.png" alt="...">
                <div class="caption text-center">
                    <h3>Glass Mapper</h3>
                    <p class="text-justify">
                        In order to implement the object relational mapper between the Sitecore data template and C# class, I found the Glass Mapper as the best alternative to do that.
                    </p>
                    <p>
                        @Html.ActionLink("View Path", "GlassMapper", "Tech", null, new { @class = "btn btn-primary" })
                        <a href="http://www.glass.lu/" target="_blank" class="btn btn-warning" role="button">Glass Mapper</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/App_Themes/Images/Icones/TDS.png" alt="...">
                <div class="caption text-center">
                    <h3>TDS</h3>
                    <p class="text-justify">
                        The source control used to share and centralize the Sitecore’s project with the rest of team. Also, it is helpful to generate the model object thought T4 template.
                    </p>                   
                    <p>
                        @Html.ActionLink("View Path", "TeamDevelopmentSitecore", "Tech", null, new { @class = "btn btn-primary" })
                        <a href="https://www.hhogdev.com/products/team-development-for-sitecore/overview.aspx" target="_blank" class="btn btn-warning" role="button">TDS</a>
                    </p>
                    
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/App_Themes/Images/Icones/Sitecore/Sitecore.png" alt="...">
                <div class="caption text-center">
                    <h3>Sitecore</h3>
                    <p>
                        The Content Management System (CMS) platform used to build the Athenahealth website.  I have implemented the AthenaTask demo on it. 
                    </p>
                    <p>
                        @Html.ActionLink("View Path", "Sitecore", "Tech", null, new { @class = "btn btn-primary" })
                        <a href="http://www.sitecore.net/" target="_blank" class="btn btn-warning" role="button">Sitecore</a>

                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/App_Themes/Images/Icones/TFS.png" alt="...">
                <div class="caption text-center">
                    <h3 >Team Foundation Server </h3>
                    <p class="text-justify">
                        In order to manage the development time on this project I decided to use the TFS. I found it very useful to keep all development historic.
                    </p>
                    <p>
                        @Html.ActionLink("View Path", "TeamFoundationServer", "Tech", null, new { @class = "btn btn-primary" })
                        <a href="https://athenahealth.visualstudio.com/" target="_blank" class="btn btn-warning" role="button">TFS</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/App_Themes/Images/Icones/windowsazure.png" alt="...">
                <div class="caption text-center">
                    <h3>Windows Azure</h3>
                    <p class="text-justify">
                        The cloud platform that provide us Infrastructure as Service to host our website and implement the CD and CI.
                    </p>
                    <p>
                        @Html.ActionLink("View Path", "WindowsAzure", "Tech", null, new { @class = "btn btn-primary" })
                        <a href="https://portal.azure.com/" target="_blank" class="btn btn-warning" role="button">Windows Azure</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

AhTask/AhTask.Web/Views/OctopusDeploy/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutTech.cshtml";
}

<h2>Index</h2>

AhTask/AhTask.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AhTask", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Tech", "Index", "Tech", new {area=" " }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>
        
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AhTask</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AhTask/AhTask.Web/Views/Shared/_LayoutSitecore.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AhTask", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Tech", "Index", "Tech", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AhTask</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AhTask/AhTask.Web/Views/Shared/_LayoutTech.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AhTask", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Tech", "Index", "Tech", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">

        <div class="row">
            <div class="col-lg-3 col-md-3">
                <ul class="nav nav-pills nav-stacked">
                    <li role="presentation" class="active">@Html.ActionLink("Home","Index","Tech")</li>
                    <li role="presentation">@Html.ActionLink("Sitecore", "Sitecore", "Tech")</li>
                    <li role="presentation">@Html.ActionLink("GitHub", "GitHub", "Tech")</li>
                    <li role="presentation" >@Html.ActionLink("TeamCity", "TeamCity", "Tech")</li>
                    <li role="presentation" >@Html.ActionLink("Octopus Deploy", "OctopusDeploy", "Tech")</li>
                    <li role="presentation" >@Html.ActionLink("Team Foundation Server", "TeamFoundationServer", "Tech")</li>
                    <li role="presentation" >@Html.ActionLink("Team Development Sitecore", "TeamDevelopmentSitecore", "Tech")</li>                   
                    <li role="presentation" >@Html.ActionLink("Windows Azure", "WindowsAzure", "Tech")</li>
                    <li role="presentation" >@Html.ActionLink("Glass Mapper", "GlassMapper", "Tech")</li>
                </ul>

            </div>
            <div class="col-lg-9 col-md-9">
                <div class="row">
                    @RenderBody()
                </div>
                
            </div>
            
        </div>

       
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AhTask</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AhTask/AhTask.Web/Views/TeamCity/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

AhTask/AhTask.Web/Views/TeamDevelopmentSitecore/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

AhTask/AhTask.Web/Views/TeamFoundationServer/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>